### ISSUE TITLE
shopify integration problem

### ISSUE THREAD

**Issue by T1fraser** [VivaPayments/API#1187]
We have followed the Vivawallet intergration set up instructions  and have our store token but when we are get to point 5 see below:-

'In your current browser window, open http://www.shopify.com/admin/authorize_gateway/1041324 to display the Recently accessed stores page.'

the link takes us to one of our other shopify shops and not pure-health-and-nutrition-myshopify.com 
this is the store details we put in the request for the store token.  
we need to get it sorted so it takes us to the right shopify store and we can finish added Vivawallet as our payment gateway.what should we do?
Thank you

**Comment by matthewrgourd** [comment]
Hi @T1fraser I think (in the same browser) you need to log out of the incorrect Shopify shop and log in instead to pure-health-and-nutrition-myshopify.com then rerun the procedure. Try that and get back to us if any further issues!

**Comment by T1fraser** [comment]
ok I have done that, but now when I click on install payment it doesn't
take me to the Confirmation popup, but straight to this

[image: Screen Shot 2019-11-01 at 14.08.35.png]




and I can't get the Vivawallet to install?

Tinker









Accounts Team.






accounts@foot-logic.co.uk | | www.foot-logic.co.uk | Tel 0131 339 6516



This e-mail and any attachments are confidential and contain proprietary
information, some or all of which may be legally privileged. It is intended
solely for the use of the individual or entity to which it is addressed. If
you are not the intended recipient, please notify the author immediately by
telephone or by replying to this e-mail, and then delete all copies of the
e-mail on your system. If you are not the intended recipient, you must not
use, disclose, distribute, copy, print or rely on this e-mail. Any views,
opinions, conclusions or other information in this message which do not
relate to the business of this firm are not authorised by us. Whilst we
have taken reasonable precautions to ensure that this e-mail and any
attachment has been checked for viruses, we cannot guarantee that they are
virus free and we cannot accept liability for any damage sustained as a
result of software viruses. We would advise that you carry out your own
virus checks, especially before opening an attachment.

Foot Logic Limited, registered in Scotland (SC531431). Registered office :
14 Newton Place, Glasgow, G3 7PY

The views expressed in this e-mail are not necessarily those of Foot Logic
Limited and unless this e-mail is sent in connection with its business,
Foot Logic Limited does not accept any responsibility for the contents of
this e-mail.

**Comment by matthewrgourd** [comment]
Sorry the last screenshot didn't come through very well. Can you try again?

Also, after logging out of the incorrect Shopify shop and logging in to pure-health-and-nutrition-myshopify.com did you open http://www.shopify.com/admin/authorize_gateway/1041324 again?

**Comment by T1fraser** [comment]
yes and the screenshot I sent you was what happened will send it again

Accounts Team.






accounts@foot-logic.co.uk | | www.foot-logic.co.uk | Tel 0131 339 6516



This e-mail and any attachments are confidential and contain proprietary
information, some or all of which may be legally privileged. It is intended
solely for the use of the individual or entity to which it is addressed. If
you are not the intended recipient, please notify the author immediately by
telephone or by replying to this e-mail, and then delete all copies of the
e-mail on your system. If you are not the intended recipient, you must not
use, disclose, distribute, copy, print or rely on this e-mail. Any views,
opinions, conclusions or other information in this message which do not
relate to the business of this firm are not authorised by us. Whilst we
have taken reasonable precautions to ensure that this e-mail and any
attachment has been checked for viruses, we cannot guarantee that they are
virus free and we cannot accept liability for any damage sustained as a
result of software viruses. We would advise that you carry out your own
virus checks, especially before opening an attachment.

Foot Logic Limited, registered in Scotland (SC531431). Registered office :
14 Newton Place, Glasgow, G3 7PY

The views expressed in this e-mail are not necessarily those of Foot Logic
Limited and unless this e-mail is sent in connection with its business,
Foot Logic Limited does not accept any responsibility for the contents of
this e-mail.

**Comment by T1fraser** [comment]
Accounts Team.



[image: Screen Shot 2019-11-01 at 14.08.35.png]




accounts@foot-logic.co.uk | | www.foot-logic.co.uk | Tel 0131 339 6516



This e-mail and any attachments are confidential and contain proprietary
information, some or all of which may be legally privileged. It is intended
solely for the use of the individual or entity to which it is addressed. If
you are not the intended recipient, please notify the author immediately by
telephone or by replying to this e-mail, and then delete all copies of the
e-mail on your system. If you are not the intended recipient, you must not
use, disclose, distribute, copy, print or rely on this e-mail. Any views,
opinions, conclusions or other information in this message which do not
relate to the business of this firm are not authorised by us. Whilst we
have taken reasonable precautions to ensure that this e-mail and any
attachment has been checked for viruses, we cannot guarantee that they are
virus free and we cannot accept liability for any damage sustained as a
result of software viruses. We would advise that you carry out your own
virus checks, especially before opening an attachment.

Foot Logic Limited, registered in Scotland (SC531431). Registered office :
14 Newton Place, Glasgow, G3 7PY

The views expressed in this e-mail are not necessarily those of Foot Logic
Limited and unless this e-mail is sent in connection with its business,
Foot Logic Limited does not accept any responsibility for the contents of
this e-mail.

**Comment by matthewrgourd** [comment]
The screenshot's still not coming through, unfortunately. Is it this screen that comes up?

![payment-providers](https://user-images.githubusercontent.com/44943019/68033548-d25c7480-fcb7-11e9-9f43-669e4837bc46.png)

**Comment by T1fraser** [comment]
simialar

ours doesn't have the accept credit cards just Paypal and what's below.
Can you see this picture?


[image: Screen Shot 2019-11-01 at 14.58.45.png]



Accounts Team.






accounts@foot-logic.co.uk | | www.foot-logic.co.uk | Tel 0131 339 6516



This e-mail and any attachments are confidential and contain proprietary
information, some or all of which may be legally privileged. It is intended
solely for the use of the individual or entity to which it is addressed. If
you are not the intended recipient, please notify the author immediately by
telephone or by replying to this e-mail, and then delete all copies of the
e-mail on your system. If you are not the intended recipient, you must not
use, disclose, distribute, copy, print or rely on this e-mail. Any views,
opinions, conclusions or other information in this message which do not
relate to the business of this firm are not authorised by us. Whilst we
have taken reasonable precautions to ensure that this e-mail and any
attachment has been checked for viruses, we cannot guarantee that they are
virus free and we cannot accept liability for any damage sustained as a
result of software viruses. We would advise that you carry out your own
virus checks, especially before opening an attachment.

Foot Logic Limited, registered in Scotland (SC531431). Registered office :
14 Newton Place, Glasgow, G3 7PY

The views expressed in this e-mail are not necessarily those of Foot Logic
Limited and unless this e-mail is sent in connection with its business,
Foot Logic Limited does not accept any responsibility for the contents of
this e-mail.

**Comment by matthewrgourd** [comment]
Are you getting a 'store not found' message at any point? No the screenshots are still not coming through...

**Comment by T1fraser** [comment]
No can you please deal with Gordon Fraser on gordon@foot-logic.co.uk on
this as he has taken it over from me.  He builds all our websites.

Accounts Team.






accounts@foot-logic.co.uk | | www.foot-logic.co.uk | Tel 0131 339 6516



This e-mail and any attachments are confidential and contain proprietary
information, some or all of which may be legally privileged. It is intended
solely for the use of the individual or entity to which it is addressed. If
you are not the intended recipient, please notify the author immediately by
telephone or by replying to this e-mail, and then delete all copies of the
e-mail on your system. If you are not the intended recipient, you must not
use, disclose, distribute, copy, print or rely on this e-mail. Any views,
opinions, conclusions or other information in this message which do not
relate to the business of this firm are not authorised by us. Whilst we
have taken reasonable precautions to ensure that this e-mail and any
attachment has been checked for viruses, we cannot guarantee that they are
virus free and we cannot accept liability for any damage sustained as a
result of software viruses. We would advise that you carry out your own
virus checks, especially before opening an attachment.

Foot Logic Limited, registered in Scotland (SC531431). Registered office :
14 Newton Place, Glasgow, G3 7PY

The views expressed in this e-mail are not necessarily those of Foot Logic
Limited and unless this e-mail is sent in connection with its business,
Foot Logic Limited does not accept any responsibility for the contents of
this e-mail.

**Comment by T1fraser** [comment]
Hi Matt

here is the screenshot of what we are seeing:

[image: image.png]
Regards,

Gordon

Gordon Fraser


Foot Logic & Mountain Sports


gordon@foot-logic.co.uk : +44 7977 431317


The Future Now™is a trademark of Foot Logic Limited.

**Comment by matthewrgourd** [comment]
Unfortunately we don't provide an email or telephone support service, only our help via our public GitHub here. Please get him to add any input to the issue you've already raised. Thanks!

**Comment by T1fraser** [comment]
Hi Matt, here is the page:https://www.screencast.com/t/Yh0af4opY

**Comment by matthewrgourd** [comment]
Hi @T1fraser I'm sorry I can't recreate the issue. Is your store at http://pure.health.and.nutrition.myshopify.com/ fully set up?

**Comment by T1fraser** [comment]
Yes, it is. You can see it via www.purehealthandnutrition.com

**Comment by matthewrgourd** [comment]
You mentioned about having a web developer. Can you get him to have a look? At the moment I'm having issues seeing what the problem is but I'll raise with our Shopify expert and see if he can do anything.

**Comment by T1fraser** [comment]
We dont have a web developer. We work with Shopify as it is their theme. I am talking to them at the moment.

**Comment by matthewrgourd** [comment]
The only other thing I can think of right now is if you clear your cache and cookies in your browser before following the [installation procedure](https://developer.vivawallet.com/e-commerce-plugins/shopify/) again from the beginning.

**Comment by T1fraser** [comment]
ok, were there. Found it. What do we put in "Merchant ID'?

**Comment by matthewrgourd** [comment]
[Log in](https://www.vivapayments.com/en-gb/signin) to Viva Wallet banking app and go to [Profile / Settings / API access](https://www.vivawallet.com/wp-content/uploads/2019/03/how-to-find-merchant-id-2.png).

**Comment by T1fraser** [comment]
we found the merchant id and have activated it in test mode.

**Comment by matthewrgourd** [comment]
You will also need your store token which you request via [this form](https://viva.microsoftcrmportals.com/shopify) and we email to you.

**Comment by matthewrgourd** [comment]
Test mode will need to be disabled.

**Comment by T1fraser** [comment]
Hi Matt, in order to integrate our site with Xero accounting we require this info from you: https://www.screencast.com/t/IhcVEXAI

**Comment by T1fraser** [comment]
Hi Matt, if you can send this tonight that would be really appreciated.

**Comment by matthewrgourd** [comment]
I'm sorry, I don't believe we support this type of integration, but @dmihos should be able to confirm for you.

**Comment by T1fraser** [comment]
Hi Matt,

that is VERY disappointing and bit surprising as Xero have 1m subscribers
around the Globe and Shopify just announced they also have 1m users. We
work with both companies.  Perhaps they should be working with Xero as they
are working with Shopify.

Tinker

Regards,

Accounts Team.






accounts@foot-logic.co.uk | | www.foot-logic.co.uk | Tel 0131 339 6516



This e-mail and any attachments are confidential and contain proprietary
information, some or all of which may be legally privileged. It is intended
solely for the use of the individual or entity to which it is addressed. If
you are not the intended recipient, please notify the author immediately by
telephone or by replying to this e-mail, and then delete all copies of the
e-mail on your system. If you are not the intended recipient, you must not
use, disclose, distribute, copy, print or rely on this e-mail. Any views,
opinions, conclusions or other information in this message which do not
relate to the business of this firm are not authorised by us. Whilst we
have taken reasonable precautions to ensure that this e-mail and any
attachment has been checked for viruses, we cannot guarantee that they are
virus free and we cannot accept liability for any damage sustained as a
result of software viruses. We would advise that you carry out your own
virus checks, especially before opening an attachment.

Foot Logic Limited, registered in Scotland (SC531431). Registered office :
14 Newton Place, Glasgow, G3 7PY

The views expressed in this e-mail are not necessarily those of Foot Logic
Limited and unless this e-mail is sent in connection with its business,
Foot Logic Limited does not accept any responsibility for the contents of
this e-mail.
