### ISSUE TITLE
Reference number CC-1375538

### ISSUE THREAD

**Issue by vassilismon85** [VivaPayments/API#1908]
I am trying to link Viva Payment for my customer, using the Simple Checkout payment method.
I have created 2 payment sources.
The 1st one with code 9393 could not be validated, because our actual domain is www.onlinefood.gr/spitikomarousi but we are not allowed to input "/" in the field. We have sent several emails to your support departement explaining that.
For that reason we created a new payment source, code 9831, with the domain spitikomarousi.onlinefood.gr. But actually, in order for you to check our content, when you visit this url we redirect it to www.onlinefood.gr/spitikomarousi. This was the way we thought it will help you find our eshop.
We received confirmation email from merchants@vivawallet.com that you searched our site and found all the appropriate content., with reference number CC-1375120. 

When we try to make an online payment, I see the following error on the browser's console: "The following error occured: The specified api action is disabled for the merchant *****, please consult the documentationERROR" (error.jpg)
![Error](https://user-images.githubusercontent.com/69846515/95603505-0bbc6900-0a5f-11eb-8669-22e0f70f9059.jpg)

When we reported the error, we recieved an email (reference: CC-1375538), to open an Issue on the developer portal, and reply to the following:
- Plugin and version: We are not using any plugin. The eshop is custom made from us.
- Screenshot with payment module: attached (Viva.jpg)
![Viva](https://user-images.githubusercontent.com/69846515/95603979-b5035f00-0a5f-11eb-8456-cf6eb4b30b03.JPG)
The error that we recieve is the error.jpg which is already attached.

I am wondering whether you use the domain that we provice you for the final approval as firewall also. In the 9393 payment source we have the www.onlinefood.gr domain, but if the approval is on the 9831 payment source, the domain is spitikomarousi.onlinefood.gr but finally the payment is made through www.onlinefood.gr/spitikomarousi/basket/$language. So, in the second case we have different sub domains. Our eshop's actual url is www.onlinefood.gr/spitikomarousi.

I am waiting for your reply as soon as possible, because it is almost a whole week that we can advertise oue eshop.

**Comment by matthewrgourd** [comment]
Hi @vassilismon85, sorry to hear you're experiencing difficulties. First of all, are you attempting to implement our [marketplace solution](https://developer.vivawallet.com/online-marketplace/) because that uses [Native](https://developer.vivawallet.com/online-checkouts/native-checkout-v2/) rather than Simple Checkout? For this you only create one checkout and that would be attached to http://www.onlinefood.gr/ through which all payments are collected. Please provide as much detail as possible about what the business wants to achieve then I will be able to help you. Thanks.

**Comment by vassilismon85** [comment]
I believe that it is very clear that we are using the Simple Check payment method. I even included in the initial post a screenshot with the payment module's source code. I am not sure which are the additional details that I must provide you. I have sent you the source code and the screenshot with the error. I have also described you in detail the payment sources that I have opened for my customer, including my remarks concerning the domain and subdomain. My customer is already pushing me to change the payment gatewayt to a different company, because as you can see from the reference numbers provided, I am having this problem for almost 10 days now. The reference numbers are from your support system through email. I need to implement the same solution for 2 more customers of mine. I need specif instructions or a solution by you

**Comment by matthewrgourd** [comment]
Hi @vassilismon85 the reason I asked you the question about our marketplace solution is because one of our sales team mentioned this to me last week and it was exactly the same merchant. So I think they may want to do that. Can you check with them and get back to me?

In answer to your Simple Checkout question, all of our payment solutions require a separate domain to be set up. So you can have a payment source for http://www.onlinefood.gr/ but not for http://www.onlinefood.gr/spitikomarousi. This is the expected behaviour. What you're asking for is not possible I'm afraid.

**Comment by vassilismon85** [comment]
Yes, but with the same method, I have already implemented other sites, which are currently working fine. Because you didn't want a payment source in the past.

**Comment by vassilismon85** [comment]
For that reason, I have created a payment source with the domain spitikomarousi.onlinefood.gr. But finally the payment is made through www.onlinefood.gr/spitikomarousi/basket/$language. This is not possible either? Of course, the domain that I will give you in the payment source it cannot be the same from where the payment is sent. You cannot support different subdomains also? So, for me the solution is to change the payment gateway to a different company than Viva

**Comment by matthewrgourd** [comment]
Hi @vassilismon85, from the [online marketplace documentation](https://developer.vivawallet.com/online-marketplace), I'm under the impression that the below steps would apply:

1. Customer places an order on the marketplace platform. They can purchase items from different sellers and include them in one order.
2. Customer proceeds to payment which is handled by Viva Wallet and held in escrow.
3. Authorized marketplace users transfer the respective funds from Viva Wallet escrow account to seller merchant accounts. At the same time, the commission fees are transferred to the marketplace merchant account.

So payments from the seller www.onlinefood.gr/spitikomarousi would be collected by www.onlinefood.gr.

**Comment by vassilismon85** [comment]
When I use this payment source, I get the following error on the browser's console: "The following error occured: The specified api action is disabled for the merchant dbded8cd-e3d0-4cbb-8df2-2f12f59bf640, please consult the documentationERROR" (error.jpg)
It is also attached above

**Comment by matthewrgourd** [comment]
Hi @vassilismon85 that error normally means that the Simple Checkout API needs enabling for the merchant. However, I checked using that ID and it is already enabled for that merchant. But if you're attempting to implement the online marketplace you should be using our Native rather than Simple Checkout solution. Apologies for any confusion but I'm still not certain what it is you're attempting to do. Will there be more sellers like http://www.onlinefood.gr/spitikomarousi attached to the http://www.onlinefood.gr marketplace in the future?

**Comment by vassilismon85** [comment]
I am only using the Simple Checkout API. All my eshops are under the domain https://www.onlinefood.gr. But all actual eshop url's are  https://www.onlinefood.gr/$shopname. It is not only for the .../spitikomarousi. The same implemantation is for all my customers. My previous customers are working just fine, but when we put them online you didn't have in the simple checkout instructions the required step to add a payment source at that time. So, I have this problem with 3 new that I am trying to set up. The eshop .../spitikomarousi is just one of three.

**Comment by matthewrgourd** [comment]
Hi @vassilismon85, ok, that's very useful info. So I can investigate a bit more, can you let me have the web addresses of one or two of the merchants you've already set up using the described method?

**Comment by vassilismon85** [comment]
Because you told me that you see that it is already enabled for that merchant, I just tried again, without changin anything and the payment worked. From Wednesday until yesterday it was not working. But now it just worked

**Comment by vassilismon85** [comment]
Did it just take so many days to enabled?

**Comment by vassilismon85** [comment]
I just made a payment with my credit card and it worked

**Comment by matthewrgourd** [comment]
The Simple Checkout API, once enabled, is available instantly. However, payment sources can take up to 2 working days to become active.

**Comment by vassilismon85** [comment]
Yes, but nobody told me that, and I have sent over 4 emails explaining the same problem. Nobody said nothing about 2 working days. Ok. Thank you for your time

**Comment by vassilismon85** [comment]
For my next eshops, do you suggest openig the payment source with the subdomain, like I did with the domain spitikomarousi.onlinefood.gr?

**Comment by matthewrgourd** [comment]
Sure, if it was ok for you before, please choose that option. Once again, sorry for the confusion before. We got some wires crossed at this end about your requirements.

**Comment by vassilismon85** [comment]
No problem. I was getting tired with it because I didn't have the correct information. Is it possbile for you to also check the payment source mentioned above? I can give the whatever data you need about this merchant with domain stoxeri.onlinefood.gr

**Comment by matthewrgourd** [comment]
Hi there, payment source 1465 for stoxeri.onlinefood.gr is active. For future reference, when setting up Simple Checkout on a new store, I think you can still use `data-vp-sourcecode="Default"` which comes with every account and is enabled already.

**Comment by vassilismon85** [comment]
Yes I have the option to use default, I just do it in order to have the customer's logo on your pop up window. It looks nicer :)

**Comment by vassilismon85** [comment]
I just tried to pay online in stoxeri.onlinefood.gr and I got exactly the same error. The following error occured: The specified api action is disabled for the merchant 80fa9a1c-6d9a-4363-b986-834b654e7902, please consult the documentationERROR. Maybe it is not enabled yet?

**Comment by vassilismon85** [comment]
I remind you that my payment is actually from the https://www.onlinefood.gr/stoxeri/basket/gr url. I used the subdomain stoxeri.onlinefood.gr for the authentication of the content

**Comment by vassilismon85** [comment]
Nor the data-vp-sourcecode="Default" is working. Same error

**Comment by matthewrgourd** [comment]
Hi @vassilismon85 sorry, there are two separate things, activation of payment source and enablement of API. Unfortunately I didn't check the latter but it is done now!

**Comment by vassilismon85** [comment]
Ok. Just checked it. It is working fine. Thank you very much
